services:
  - type: web
    name: keii-cv-api
    env: docker
    repo: https://github.com/trunghuydev/Portfolio_BE
    branch: main
    dockerfilePath: ./src/Dockerfile
    rootDir: src
    plan: free
    autoDeploy: false
